# Generated by Django 5.0.12 on 2025-02-23 12:11

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_blogpage_image_alter_blogpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('last_posts', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Last Posts'}), 1: ('wagtail.blocks.IntegerBlock', (), {'default': 5}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('number_of_posts', 1)]], {})}),
        ),
    ]
