# Generated by Django 5.0.12 on 2025-02-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_socialmediasettings_copyrightsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copyrightsettings',
            name='year',
            field=models.IntegerField(default=2025),
        ),
    ]
