# Generated by Django 5.0.12 on 2025-02-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_alter_copyrightsettings_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediasettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
